config/routes.rb
Rails.application.routes.draw do
            
  resources :forums, only: [:index, :show], :path => "forum"
  resources :discussions
  resources :posts, only: [:edit, :new, :create, :update]    
  resources :pearls
  
  resources :comments, only: [:create]
       
  root to: 'pages#home'
  
  get 'benutzer/:id' => 'users#show', as: "user"  
  devise_for :users   
  
  get 'wer-bin-ich', to: 'pages#who', as: "who_am_i"
  get 'was-biete-ich-an', to: 'pages#what', as: "what_do_i_offer"   
  get 'kontakt', to: 'pages#contact', as: "contact"  
  post 'kontaktiert', to: 'pages#contacted', as: "contacted"
  

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  is_impressionable
  
  has_many :discussions, dependent: :destroy
  
  has_many :posts, :through => :discussions
  
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]
  impressionist :actions=>[:show]
  
  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    impressionist(@forum)
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.friendly.find(params[:id])
      @discussions = @forum.discussions.paginate(:page => params[:page], :per_page => 6).includes(:user)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:name, :description)
    end
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/index.html.erb
<% title "Forum" %>

<h3>Forum</h3>

<%= render "users/userinfo" %>

<div class="panel panel-success">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong>Forum</strong></div>

  <!-- Table -->
  <table class="table table-hover">
    <thead>
      <tr>        
        <th>Thema</th>
        <th>Diskussionen</th>
        <th>Beiträge</th>        
      </tr>
    </thead>
    <tbody>    	    
    	<% @forums.each do |forum| %>
    		<tr data-link="<%= forum_path(forum) %>" >
        		<td><strong><%= forum.name %></strong><br/><%= forum.description %></td>
        		<td><%= forum.discussions.count %></td>
        		<td><%= (forum.posts.count + forum.discussions.count) %></td>
      		</tr>
    	<% end %>    	
    </tbody>
  </table>  
</div>  
<br/>
Anzahl an registrierten Benutzer: <strong><%= User.all.count %></strong>

app/views/forums/show.html.erb
<% title "Forum: " + @forum.name %>

<h3>Übersicht</h3>

<%= render "users/userinfo" %>

<div class="panel panel-success">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong><%= @forum.name %></strong> (<%= @forum.discussions.count %> Diskussionsthemen) 
  	<%= link_to 'Neue Diskussion', new_discussion_path(forum_id: @forum.id), :class => "btn btn-xs btn-success spaced-btn pull-right", data: { no_turbolink: true } %>	
  </div>

  <!-- Table -->
  <table class="table table-hover">
    <thead>
      <tr>      	
      	<th><strong>Diskussionsthema</strong></th>                
        <th>Beiträge</th>           
      </tr>
    </thead>
    <tbody>    	    
    	<% @discussions.each do |discussion| %>
    		<tr data-link="<%= discussion_path(discussion) %>" >
        		<td><strong><%= discussion.title %></strong><br/><small>erstellt durch <%= link_to discussion.user.username, current_user %> am <%= discussion.created_at %></small></td>
        		<td><%= (discussion.posts.count + 1) %></td>        		    		      
      		</tr>
    	<% end %>    	
    </tbody>
  </table>  
</div>  
<%= will_paginate @discussions, renderer: BootstrapPagination::Rails %> <br/>

<%= link_to 'Neue Diskussion', new_discussion_path(forum_id: @forum.id), :class => "btn btn-xs btn-success spaced-btn", data: { no_turbolink: true } %> <%= link_to 'Alle Foren', forums_path, :class => "btn btn-info btn-xs spaced-btn" %>