config/routes.rb
Rails.application.routes.draw do
            
  resources :forums, only: [:index, :show], :path => "forum"
  resources :discussions
  resources :posts, only: [:edit, :new, :create, :update]    
  resources :pearls
  
  resources :comments, only: [:create]
       
  root to: 'pages#home'
  
  get 'benutzer/:id' => 'users#show', as: "user"  
  devise_for :users   
  
  get 'wer-bin-ich', to: 'pages#who', as: "who_am_i"
  get 'was-biete-ich-an', to: 'pages#what', as: "what_do_i_offer"   
  get 'kontakt', to: 'pages#contact', as: "contact"  
  post 'kontaktiert', to: 'pages#contacted', as: "contacted"
  

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :user
  belongs_to :forum
  
  has_many :posts, dependent: :destroy
  
  is_impressionable
  
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  validates_length_of :title, :minimum => 5
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]  
  impressionist :actions=>[:show]
  
  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.includes(:user).all
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    impressionist(@discussion)
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new(:forum_id => params[:forum_id], :user_id => current_user.id)    
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)
    @discussion.user = current_user
    
    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion      
      @discussion = Discussion.includes(posts: :user).friendly.find(params[:id])      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:title, :firstpost, :user_id, :forum_id)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= tinymce %>

<%= simple_form_for([@discussion]) do |f| %>  
  <div class="form-inputs">  	
    <%= f.input :title %>
    
    <%= f.label :firstpost, 'Beitrag', :required => true %>    	
	<%= f.text_area :firstpost, class: "tinymce", :rows => 25, :cols => 120 %>	

    <%= f.association :user, :as => :hidden %>

    <%= f.association :forum, :as => :hidden  %>
  </div>
  <br/>  
  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary btn-sm"  %>
  </div>
<% end %>

app/views/discussions/_short_user.html.erb
<div class="right_border">
	erstellt von <strong><%= link_to user.username, user %></strong>
	
	<br/>
	<small>Mitglied seit <%= user.created_at %></small>
</div>

app/views/discussions/_show_discussion.html.erb
<h3>Übersicht</h3>

<%= render "users/userinfo" %>

<div class="panel panel-success">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong><%= discussion.title %></strong>
  	<%= link_to 'Neuer Beitrag', new_post_path(discussion_id: discussion.id), :class => "btn btn-xs btn-success spaced-btn pull-right", data: { no_turbolink: true } %>
  </div>

	<div class="container-fluid">
		<div class="row info_box">
			<div class="col-xs-3">  
	        	<%= render partial: "discussions/short_user", locals: { user: discussion.user} %>
	        </div>
	        <div class="col-xs-9 nopadding">  
				<small>verfasst <%= discussion.created_at %></small>
				<hr>						        				
	        	<%= raw discussion.firstpost %>
	        </div>
	    </div>	   
	     	   
    	<% discussion.posts.each do |post| %>
    		<div class="row info_box">
				<div class="col-xs-3">					
		        	<%= render partial: "discussions/short_user", locals: { user: post.user} %>		        						
		        </div>
		        		        		       
		        <div class="col-xs-9 nopadding">  		        	
		        	<small>verfasst <%= post.created_at %></small>		        	
		        	<% if ((user_signed_in? && (current_user.id == post.user_id)) || current_user_admin?) %>
						<ul class="list-inline pull-right">
							<li>
								<%= link_to edit_post_path(post), data: { no_turbolink: true }, :class => "btn-warning btn-sm" do %>
									<i class="glyphicon, glyphicon glyphicon-pencil"></i>
								<% end %>
							</li>
							<li> 
								<%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-danger btn-sm"  do %>
									<i class="glyphicon, glyphicon glyphicon-trash"></i>
								<% end %>
							</li>
						</ul> 						
					<% end %>
					<hr>						        
		        	<%= raw post.body %>
		        	<% if (post.updated_at > post.created_at) %>
		        		<br/>
		        		<br/>
		        		<small>zuletzt bearbeitet <%= post.updated_at %></small>
		        	<% end %>
		        </div>
		    </div>		    
    	<% end %>    	
	</div>        
</div>
<small class="pull-right">(<%= discussion.impressionist_count %> Mal gesehen)</small>  

app/views/discussions/edit.html.erb
<h3>Diskussion <strong><%= @discussion.title %></strong> bearbeiten</h3>

<%= render 'form' %>

<%= link_to 'zurück', @discussion %> 

app/views/discussions/new.html.erb
<% title "Neues Diskussionsthema anlegen" %>

<h3>Neues Diskussionsthema anlegen</h3>

<%= render 'form' %>

app/views/discussions/show.html.erb
<% title "Diskussion: " + @discussion.title %>

<%= render partial: "show_discussion", locals: { discussion: @discussion } %>

<%= link_to 'Neuer Beitrag', new_post_path(discussion_id: @discussion.id), :class => "btn btn-xs btn-success spaced-btn", data: { no_turbolink: true } %> <%= link_to 'zurück', forum_path(@discussion.forum), :class => "btn btn-info btn-xs spaced-btn" %>