config/routes.rb
Rails.application.routes.draw do
            
  resources :forums, only: [:index, :show], :path => "forum"
  resources :discussions
  resources :posts, only: [:edit, :new, :create, :update]    
  resources :pearls
  
  resources :comments, only: [:create]
       
  root to: 'pages#home'
  
  get 'benutzer/:id' => 'users#show', as: "user"  
  devise_for :users   
  
  get 'wer-bin-ich', to: 'pages#who', as: "who_am_i"
  get 'was-biete-ich-an', to: 'pages#what', as: "what_do_i_offer"   
  get 'kontakt', to: 'pages#contact', as: "contact"  
  post 'kontaktiert', to: 'pages#contacted', as: "contacted"
  

end

app/models/pearl.rb
class Pearl < ActiveRecord::Base  
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  mount_uploader :image, ImageUploader   
  is_impressionable

  acts_as_commentable
  
  scope :next, lambda {|id| where("id > ?",id).order("id ASC") } # this is the default ordering for AR
  scope :previous, lambda {|id| where("id < ?",id).order("id DESC") }

  def next
    Pearl.next(self.id).first
  end

  def previous
    Pearl.previous(self.id).first
  end
  
end

app/controllers/pearls_controller.rb
class PearlsController < ApplicationController
  before_action :set_pearl, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :make_sure_is_owner, only: [:edit, :update, :destroy]
  impressionist :actions=>[:show]

  def index    
    @pearls = Pearl.paginate(:page => params[:page], :per_page => 6).includes(:user)
  end


  # GET /pearls/1
  # GET /pearls/1.json
  def show
    impressionist(@pearl)
    @comment = Comment.new
    @comment.commentable = @pearl       
    @comment.user = current_user    
  end

  # GET /pearls/new
  def new
    @pearl = Pearl.new
  end

  # GET /pearls/1/edit
  def edit
  end

  # POST /pearls
  # POST /pearls.json
  def create
    @pearl = Pearl.new(pearl_params)
    @pearl.user = current_user
    respond_to do |format|
      if @pearl.save
        format.html { redirect_to @pearl, notice: 'Perle wurde erfolgreich angelegt.' }
        format.json { render :show, status: :created, location: @pearl }
      else
        format.html { render :new }
        format.json { render json: @pearl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pearls/1
  # PATCH/PUT /pearls/1.json
  def update
    respond_to do |format|
      if @pearl.update(pearl_params)
        format.html { redirect_to @pearl, notice: 'Perle wurde erfolgreich bearbeitet.' }
        format.json { render :show, status: :ok, location: @pearl }
      else
        format.html { render :edit }
        format.json { render json: @pearl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pearls/1
  # DELETE /pearls/1.json
  def destroy
    @pearl.destroy
    respond_to do |format|
      format.html { redirect_to pearls_url, notice: 'Perle wurde erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pearl
    @pearl = Pearl.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pearl_params
    params.require(:pearl).permit(:user_id, :body, :title, :image, :remove_image, :comments_attributes => [:id, :comment])
  end

  def make_sure_is_owner
    @pearl = Pearl.friendly.find(params[:id]).includes(:comments)
    if (user_signed_in? && ((current_user.id == @pearl.user.id) || current_user.admin? ))

      else
      respond_to do |format|
        format.html { redirect_to pearl_path(@pearl), alert: 'Sie können nur ihre eigenen Perlen bearbeiten!' }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/pearls_helper.rb
module PearlsHelper
end

app/views/pearls/_form.html.erb
<%= tinymce %>

<%= simple_form_for(@pearl) do |f| %>
<div class="form-inputs">
	<%= f.input :title, :required => true, label: "Titel" %>

	<%= f.label :body, 'Gedanken', :required => true %>
	<%= f.text_area :body, class: "tinymce", :rows => 25, :cols => 120 %>

	<br />

	<%= f.input :image, label: "Bild" %>

	<% if @pearl.image_url.present? %>
	Remove Image
	<%= f.check_box :remove_image %>
	<%= image_tag(@pearl.image_url(:thumb)) if @pearl.image? %>
	<% end %>
</div>

<br />
<div class="form-actions">
	<%= f.button :submit, :class => "btn btn-primary btn-sm"  %>
</div>

<% end %>

app/views/pearls/_pearl_navigation.html.erb
<div class="row">
<% if pearl.previous.presence %>	
	<a href="<%= pearl_path(pearl.previous) %>">		
		<button type="button" class="btn btn-default btn-xs spaced-btn">
	  		<span class="glyphicon glyphicon-chevron-left"></span> Vorherige
		</button>
	</a>	
	<% end %>
	<%= link_to 'Übersicht', pearls_path(), :class => "btn btn-info btn-xs spaced-btn" %>
	<% if pearl.next.presence %>	
	<a href="<%= pearl_path(pearl.next) %>">		
		<button type="button" class="btn btn-default btn-xs spaced-btn">
	  		<span class="glyphicon glyphicon-chevron-right"></span> Nächste
		</button>
	</a>	
<% end %>
</div>

app/views/pearls/edit.html.erb
<h3>Ändern von "<%= @pearl.title %>"</h3>

<%= render 'form' %>
<br />
<br />
<br />
<%= link_to 'zurück', @pearl, :class => "btn btn-info btn-xs col-md-2" %>
<br />
<br />
<br />

app/views/pearls/index.html.erb
<% title "Gedanken Perlen" %>

<h3>Gedanken</h3>
<p>und solche die es wert sind zu werden</p>

<%= will_paginate @pearls, renderer: BootstrapPagination::Rails %> <br/>

<% @pearls.each do |pearl| %>
<a href="<%= pearl_path(pearl) %>" class="block_link">
	<div class="col-md-6 boxed-pearl">
		<div class="inner-pearl">
			<% if pearl.image_url.present? %>			
	        	<%= image_tag(pearl.image_url, :class => "img-responsive fixed_height") %>
	        <% end %>	        	        
	        <strong><%= pearl.title %></strong><br/>
	        von <%= pearl.user.username %>
        </div>
	</div>
</a>
<% end %>

<br/>

<%= will_paginate @pearls, renderer: BootstrapPagination::Rails %>

<% if user_signed_in? %>            	                       
	<br/>
	<br/>
	<%= link_to 'Neue Perle', new_pearl_path, :class => "btn btn-xs btn-success", data: { no_turbolink: true } %>
<% end %>

app/views/pearls/new.html.erb
<% title "Neue Gedankenperle anlegen" %>

<h3>New pearl</h3>

<%= render 'form' %>
<br/>
<%= link_to 'Back', weekly_pearls_path %>

app/views/pearls/show.html.erb
<% title "Gedankenperle: " + @pearl.title %>

<% content_for :head do %>

<meta property="og:name" content="<%= @pearl.title %>"/>
<meta property="og:type" content="<%= @pearl.body %>"/>
<meta property="og:description" content="link"/>
<% if @pearl.image_url.present? %>
	<meta property="og:picture" content="<%= @pearl.image_url(:thumb).to_s %>"/>
<% end %>
<meta property="og:url" content="<%= pearl_path(@pearl) %>"/>

<% end %>

<h3><%= @pearl.title %></h3>
von <%= @pearl.user.username %> ( <%= @pearl.impressionist_count %> Mal gesehen) 
<br/>
<%= social_share_button_tag(@pearl.title, :url => pearl_path(@pearl), :image => @pearl.image_url(:thumb).to_s,  :img => @pearl.image_url(:thumb).to_s) %>	
<br/>
<%= render partial: "pearl_navigation", locals: { pearl: @pearl} %>
<br/>

<div class="container-fluid">	
	<% if @pearl.image_url.present? %>
		<a href="<%= @pearl.image_url %>">			
    		<%= image_tag(@pearl.image_url, :class => "img-responsive") %>
    	</a>
    <% end %>	        	        
    <br />
	<div class="row">
		<%= raw @pearl.body %>
	</div>	     
    
    <br />
    
    <% if @pearl.comments.any? %>
    	<br />
	    <div class="row">
	    	<%= render partial: "comments/show", locals: { comments: @pearl.comments} %>
	    </div>	   	
    <% end %>   
    
    <% if ((user_signed_in? && (current_user.id == @pearl.user_id)) || current_user_admin?) %>		
	    <div class="row">
	    	 <%= render partial: "comments/form", locals: { comment: @comment} %> 		
		</div>	   		
	<% end %>
        
</div>
<br/>


<% if ((user_signed_in? && (current_user.id == @pearl.user_id)) || current_user_admin?) %>
<br/>
<br/>
<br/>			
	<div class="btn-toolbar" data-no-turbolink>		
		<%= link_to 'Ändern', edit_pearl_path(@pearl), data: { no_turbolink: true }, :class => "btn btn-warning btn-xs spaced-btn" %> 
		<%= button_to 'Löschen', @pearl, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs spaced-btn" %>
	</div>
<% end %>