config/routes.rb
Rails.application.routes.draw do
            
  resources :forums, only: [:index, :show], :path => "forum"
  resources :discussions
  resources :posts, only: [:edit, :new, :create, :update]    
  resources :pearls
  
  resources :comments, only: [:create]
       
  root to: 'pages#home'
  
  get 'benutzer/:id' => 'users#show', as: "user"  
  devise_for :users   
  
  get 'wer-bin-ich', to: 'pages#who', as: "who_am_i"
  get 'was-biete-ich-an', to: 'pages#what', as: "what_do_i_offer"   
  get 'kontakt', to: 'pages#contact', as: "contact"  
  post 'kontaktiert', to: 'pages#contacted', as: "contacted"
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Einfach machen Kontaktformular",
      :to => "maro.bader@gmail.com",
      :reply_to => '#{email}',
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :user
  belongs_to :forum
  
  has_many :posts, dependent: :destroy
  
  is_impressionable
  
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  validates_length_of :title, :minimum => 5
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  is_impressionable
  
  has_many :discussions, dependent: :destroy
  
  has_many :posts, :through => :discussions
  
end

app/models/pearl.rb
class Pearl < ActiveRecord::Base  
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  mount_uploader :image, ImageUploader   
  is_impressionable

  acts_as_commentable
  
  scope :next, lambda {|id| where("id > ?",id).order("id ASC") } # this is the default ordering for AR
  scope :previous, lambda {|id| where("id < ?",id).order("id DESC") }

  def next
    Pearl.next(self.id).first
  end

  def previous
    Pearl.previous(self.id).first
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :discussion
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  extend FriendlyId
  friendly_id :username, use: :slugged
         
  has_many :posts
  has_many :discussions
  
  attr_accessor :login
                  
  validates_length_of :username, :minimum => 4, :allow_blank => false
  validates :username, presence: true
  validates :username, :uniqueness => { :case_sensitive => false}
  
  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def who
  end

  def what
  end

  def contact
    @contact = Contact.new
  end
  
  def contacted
    @contact = Contact.new(params[:contact])    
    if simple_captcha_valid?
      @contact.request = request
      if @contact.deliver      
        flash.now[:notice] = 'Thank you for your message!'
      else
        flash.now[:error] = 'Cannot send message.'
        render :contact
      end
    else
      flash.now[:error] = 'Captche falsch.'
      render :contact
    end       
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]  

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new    
    @post = Post.new(:discussion_id => params[:discussion_id], :user_id => current_user.id)    
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post.discussion, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post.discussion, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @discussion =@post.discussion 
    @post.destroy
    respond_to do |format|
      format.html { redirect_to @discussion, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :discussion_id, :user_id)
    end
           
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.friendly.find(params[:id])
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

 def needs_sidepanel?
   current_page?(root_path) || current_page?(who_am_i_path) || current_page?(what_do_i_offer_path) || current_page?(contacted_path) 
 end

 def current_user_admin?
   user_signed_in? && current_user.admin?  
 end
 
 def title(page_title)
    content_for(:title) { page_title }
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pearls_helper.rb
module PearlsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
	Maro Bader <%= DateTime.now %>  
</div>

app/views/layouts/_header.html.erb
<div class="row">		  								
	<%= image_tag("header2.jpg", class: "img-responsive") %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav role="navigation" class="navbar navbar-inverse">    
    <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>   
    </div>
    
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav nav-pills">        	
        	<%= active_link_to "Einfach machen", root_path, :active => :exclusive, :wrap_tag => :li %>                                    
            <%= active_link_to "Was biete ich", what_do_i_offer_path, :wrap_tag => :li %>            
            <%= active_link_to "Wer bin ich", who_am_i_path, :wrap_tag => :li %>
            <%= active_link_to "Wochen-Perlen", pearls_path, :wrap_tag => :li, data: { no_turbolink: true } %>
            <%= active_link_to "Forum", forums_path, :wrap_tag => :li, data: { no_turbolink: true } %>            
        </ul>        
        <ul class="nav navbar-nav navbar-right">        	
            <%= active_link_to "Kontakt", contact_path, :wrap_tag => :li, data: { no_turbolink: true }  %>                          
            <% if user_signed_in? %>
            	<li><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>
            <% else %>
            	<li><%= link_to("Login", new_user_session_path) %></li>
            <% end %>
            
        </ul>
    </div>
</nav>

app/views/layouts/_sidepanel.html.erb
<div class="panel panel-success">
	<div class="panel-heading">Einfach <strong>mehr</strong>!</div>
	<div class="panel-body">		
		<p>
			Einfach <strong>weiter</strong>!<br />		
			<a href="http://www.hypnosetherapie-schweiz.com">Hypnose Therapie Schweiz</a><br />
			<a href="http://www.zoom-in-personam.com/">Zoom in personam (Katja Berini)</a><br />
		</p>
		<br />
		<p>
			Einfach <strong>lernen</strong>!<br />		
			<a href="http://www.hypnose-schule.ch">Hypnose Schule Schweiz</a><br />
			<a href="http://www.gesundheits-akademie.ch">Gesundheitsakademie Schweiz</a><br />
			<a href="http://www.hypnose-dachverband.ch">Hypnose Dachverband Schweiz</a><br />
		</p>
		<br />			
		<p>
			Einfach <strong>schön</strong>!<br />		
			<a href="https://www.flickr.com/photos/davikokar">Fotos vom Banner (Davide Seddio)</a><br />			
		</p>
		<br />
		<p>
			Einfach <strong>finden</strong>!<br />		
			<form role="search">
	            <div class="form-group">
	                <input type="text" placeholder="Suchbegriffe" class="form-control">
	            </div>
	        </form>				
		</p>						
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">        
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Source" %></title>
    <%= csrf_meta_tags %>
       
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
	
	<%= javascript_include_tag "application" %>	

<% if content_for?(:head) %>
  <%= yield(:head) %>
<% end %>


    
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->
	                 
  </head>
  <body>  	  	  	
	<div class="container-fluid" id="wrap">
					
		<%= render 'layouts/header' %>    
		 						    
		<div class="shadow-box">	
			<div class="row-fluids">
				<div class="container-fluid">
					<div class="row-fluids">		   		
						<%= render 'layouts/navigation' %>
					</div>			      
					<div class="row-fluids">		
												
						<% if needs_sidepanel? %>
							<div class="col-md-8">
								<%= render 'layouts/messages' %>
								
								<%= yield %>
								<br />
								<br />
								<br />
								<br />
							</div>		
							<div class="col-md-4">
								<%= render 'layouts/sidepanel' %>
							</div>		
						<% else %>	
						<div class="col-md-12">
							<%= render 'layouts/messages' %>
							
							<%= yield %>
							<br />
							<br />
							<br />
							<br />							
						</div>		
						<% end %>											
					</div><!--/row-->				
				</div>							    
			</div>
		</div>			
	</div>
		  	
  </body>
</html>

app/views/pages/contact.html.erb
<% title "Kontaktanfrage" %>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<h3>Einfach kontaktieren!</h3>

<div class="row-fluid">
	<div class="col-md-8">
		<div class="container-fluid">
			<%= simple_form_for @contact, :url => contacted_path, :html => {class: 'form-horizontal' } do |f| %>
			
			  <%=  f.input :nickname, :as => :hidden %>
			  <%=  f.input :name, label: "Ihre Name", :required => true %>
			  <%=  f.input :email, label: "Ihre Email", :required => true %>
			  <%=  f.input :message, hint: "Nutzen Sie dieses Forumlar bitte lediglich zur Kontaktaufnahme und zur Verabredung eines kostenlosen Erstgesprächs. Haben Sie bitte Verständnis, dass ich keine inhaltlichen Fragen per Email beantworten werde.", :required => true, label: "Nachricht", :as => :text, :required => false, :input_html => {:rows => 6} %>   
			  
			  <%= f.simple_captcha :label => "Enter numbers.." %>
			  
			  <%=  f.button :submit, 'Abschicken', :class=> "btn btn-primary" %>
			
			<% end %>
		</div>
	</div>		
	
	<div class="col-md-4">
		<p>
			Maro Bader<br/>
			Dorfstr. 15<br/>
			6300 Zug / CH<br/>
			<br/>
			Tel: +41 (0)77 / 49 33 589
		</p>
		<p>			
			<div id="map" style='height: 400px;'></div>
		</p>		
	</div>	
</div>
<br/>
<br/>
<br/>


<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: { }, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 47.165631,
      "lng": 8.517693,      
      "infowindow": "Dorfstr. 15, 6300 Zug",      
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(12);
});
</script>

app/views/pages/contacted.html.erb
<% title "Kontaktanfrage abgeschickt" %>

<h3>Danke für Ihr Schreiben</h3>
<p>Ich werde versuchen mich umgehend bei Ihnen zu melden</p>

app/views/pages/home.html.erb
<% title "Einfach-Leben!" %>

<%= image_tag("logo_sm.jpg", class: "img-responsive col-md-3 pull-right") %>	
<h3>Einfach machen!</h3>
<p>
	"Einfach machen!" ist eine Lebens-Philosophie, die
	<ul>
		<li>Zu mehr <strong>Ich</strong> führt</li>
		<li>Mut zur <strong>Veränderung</strong> macht</li>
		<li>Innere <strong>Ausgeglichenheit</strong> fördert</li>
		<li>Neue <strong>Wege</strong> und <strong>Möglichkeiten</strong> offenbart</li>
		<li>Aus Wünschen <strong>erreichbare Ziele</strong> macht</li>
		<li>Uns mit unserer eigenen <strong>kindlicher Leichtigkeit</strong> immer beschenkt</li>
	</ul>
</p>
<br />
<p>
	"Einfach machen!" ist aber auch <strong>Personal Coaching</strong>, <a href="http://www.hypnose-schule.ch">Hypnose-Therapie nach schweizer Model</a> und <strong>eine wundervolle Begegnung</strong> in der Innerschweiz...
</p>

<p>
	Nehmen Sie sich <strong>einfach einmal</strong> Zeit mal ein paar <%= link_to "Gedanken", pearls_path %> zu gönnen. Oder tauschen Sie sich mit mir und anderen Usern im <%= link_to "Forum", forums_path, data: { no_turbolink: true } %> aus.
</p>

app/views/pages/pearl.html.erb
<% title "Gedanken Perlen" %>

<h3>Gedanken</h3>
<p>und solche die es wert sind zu werden</p>

<%= will_paginate @pearls, renderer: BootstrapPagination::Rails %> <br/>

<% @pearls.each do |pearl| %>
<a href="<%= pearl_path(pearl) %>" class="block_link">
	<div class="col-md-6 boxed-pearl">
		<div class="inner-pearl">
			<% if pearl.image_url.present? %>			
	        	<%= image_tag(pearl.image_url, :class => "img-responsive fixed_height") %>
	        <% end %>	        	        
	        <strong><%= pearl.title %></strong><br/>
	        von <%= pearl.user.username %>
        </div>
	</div>
</a>
<% end %>

<br/>

	<%= will_paginate @pearls, renderer: BootstrapPagination::Rails %>

	<% if user_signed_in? %>            	                       
		<br/>
		<br/>
		<%= link_to 'Neue Perle', new_pearl_path, :class => "btn btn-xs btn-success", data: { no_turbolink: true } %>
	<% end %>

app/views/pages/what.html.erb
<% title "Was biete ich an" %>

<h3>Was biete ich an</h3>
Hypnose-Therapie und Personal Coaching heisst für mich, dass ich Ihnen bei folgenden Aspekten nützlich sein kann:
<ul>
	<li class="spaceditem">Ihre persönliche <strong>Leistungsfähigkeit</strong> optimieren</li>
	<li class="spaceditem">Ängste, Blockaden und Phobien erkennen und <strong>auflösen</strong></li>
	<li class="spaceditem">Das <strong>Ich</strong> stärken: <strong>Selbstbewusstsein</strong> und <strong>Selbstvertrauen</strong></li>
	<li class="spaceditem"><strong>Heilungsprozesse</strong> und die allgemeine <strong>Gesundheit</strong> fördern</li>
	<li class="spaceditem">Eigene <strong>Ressourcen</strong> und <strong>Potentiale</strong> erfolgsorientiert schärfen</li>
	<li class="spaceditem">Sich von Seelischen und körperlichen Belastungen <strong>befreien</strong></li>
	<li class="spaceditem">Ruhe, Entspannung und <strong>Leichtigkeit</strong> unterstützen</li>
	<li class="spaceditem">Unterstützung beim Beschreiten <strong>neuer Wege</strong></li>
	<li class="spaceditem">Störende <strong>Verhaltensmuster</strong> ablegen</li>
	<li class="spaceditem">Stress, Leiden und Sorgen <strong>nachhaltig</strong> angehen</li>
	<li class="spaceditem">Schmerzen und körperliche Beschwerden <strong>lindern</strong></li>
	<li class="spaceditem">Alter, Geschlecht, Herkunft, Religion... spielen bei uns keine Rolle</li>
</ul>
<p>
Lassen sie uns bei einem kostenlosen Erstgespräch die <strong>Möglichkeiten einer Zusammenarbeit</strong> ausloten. Jeder Fall ist ein <strong>Einzelfall</strong>, der einen für beide Seiten klar formulierten und erkannten Auftrag erfordert.  
</p>
<p>
In folgenden Fällen wird eine Zusammenarbeit wahrscheinlich nicht ohne weiteres erfolgen können:
<ul>
	<li class="spaceditem">Medikamentös behandelte Krankheitsbilder</li>
	<li class="spaceditem">Persönlichkeitsstörungen</li>
	<li class="spaceditem">Bei Kontraindikationen zur Hypnosetherapie</li>
	<li class="spaceditem">Ziele, die meiner Lebensphilosphie wiedersprechen</li>
</ul>
</p>

app/views/pages/who.html.erb
<% title "Wer bin ich" %>

<%= image_tag("maro_bader_sm.jpg", class: "img-responsive pull-right") %>	
<h3>Wer bin ich</h3>
<p>
Ich heisse <strong>Maro Bader</strong> und bin <a href="http://www.hypnose-schule.ch">diplomierter Hypnose-Therapeut nach schweizer Model</a>. Ich unterstütze Klienten bei ihren Prozessen, indem ich versuche die richtigen Fragen zu finden, deren Antworten Einsichten und Lösungswege beim Klienten selbst offenbaren.
</p>
<p>
Es ist mir ein Anliegen, dabei neutral und urteilsfrei zu bleiben. Sowie stets im Sinne des Klienten, seiner Weltanschauung und seiner Glaubensausrichtung zu handeln. Nur dieses führt zum Erfolg. 	
</p>
<p>
In der Praxis wie im Leben bemühe ich mich die Lebens-Philosophie <strong>"Einfach Machen!"</strong> umzusetzen. 
</p>
<br/>
<p>
	Antworten auf Fragen, die mich <strong>sehr</strong> interessieren:
	<ul>
		<li>Warum nicht?</li>
		<li>Was versprechen Sie sich denn davon, wenn wir dies machen?</li>
		<li>Ja, man kann vieles im Leben verändern, wenn man bereit ist den Weg zu gehen.</li>
		<li>Woran glauben Sie denn?</li>		
	</ul>
</p>
<br/>
<p>
	Antworten auf Fragen, die mich <strong>nicht</strong> interessieren:
	<ul>
		<li>Nein, mit Show-Hypnose hat das überhaupt nichts zu tun.</li>
	</ul>
</p>
	

app/views/simple_captcha/_simple_captcha.erb
<style type="text/css">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>

  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>

  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>

  <div class='simple_captcha_refresh_button'>
    <%= simple_captcha_options[:refresh_button] %>
  </div>
</div>